# Generated by Django 5.0.2 on 2025-12-20 06:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompositionTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(max_length=100, unique=True, verbose_name="任务ID"),
                ),
                ("video_list", models.JSONField(verbose_name="视频列表")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("progress", models.IntegerField(default=0, verbose_name="进度百分比")),
                (
                    "output_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="composed/%Y/%m/%d/",
                        verbose_name="输出文件",
                    ),
                ),
                (
                    "output_filename",
                    models.CharField(blank=True, max_length=255, verbose_name="输出文件名"),
                ),
                (
                    "total_duration",
                    models.DurationField(blank=True, null=True, verbose_name="总时长"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="composition_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "合成任务",
                "verbose_name_plural": "合成任务",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "file_path",
                    models.FileField(
                        upload_to="videos/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["mp4", "avi", "mov", "mkv", "webm"]
                            )
                        ],
                        verbose_name="视频文件",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="thumbnails/%Y/%m/%d/",
                        verbose_name="缩略图",
                    ),
                ),
                (
                    "duration",
                    models.DurationField(blank=True, null=True, verbose_name="时长"),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="文件大小(字节)"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("daoist_classic", "道教经典"),
                            ("meditation", "静心冥想"),
                            ("ritual", "道教仪式"),
                            ("teaching", "道法教学"),
                            ("chanting", "经文诵读"),
                            ("other", "其他"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="分类",
                    ),
                ),
                (
                    "upload_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                ("view_count", models.IntegerField(default=0, verbose_name="观看次数")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否激活")),
                (
                    "width",
                    models.IntegerField(blank=True, null=True, verbose_name="视频宽度"),
                ),
                (
                    "height",
                    models.IntegerField(blank=True, null=True, verbose_name="视频高度"),
                ),
                ("fps", models.FloatField(blank=True, null=True, verbose_name="帧率")),
                (
                    "bitrate",
                    models.IntegerField(blank=True, null=True, verbose_name="比特率"),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_videos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上传者",
                    ),
                ),
            ],
            options={
                "verbose_name": "视频",
                "verbose_name_plural": "视频",
                "ordering": ["-upload_time"],
            },
        ),
        migrations.CreateModel(
            name="VideoSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_index", models.IntegerField(verbose_name="排序索引")),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_selections",
                        to="videos.compositiontask",
                        verbose_name="合成任务",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selections",
                        to="videos.video",
                        verbose_name="视频",
                    ),
                ),
            ],
            options={
                "verbose_name": "视频选择",
                "verbose_name_plural": "视频选择",
                "ordering": ["order_index"],
            },
        ),
        migrations.AddIndex(
            model_name="compositiontask",
            index=models.Index(fields=["user"], name="videos_comp_user_id_2026fb_idx"),
        ),
        migrations.AddIndex(
            model_name="compositiontask",
            index=models.Index(fields=["status"], name="videos_comp_status_4cb9b4_idx"),
        ),
        migrations.AddIndex(
            model_name="compositiontask",
            index=models.Index(
                fields=["created_at"], name="videos_comp_created_c9bc32_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(
                fields=["category"], name="videos_vide_categor_c4366b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(
                fields=["uploader"], name="videos_vide_uploade_fca05f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(
                fields=["upload_time"], name="videos_vide_upload__807dc4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(
                fields=["is_active"], name="videos_vide_is_acti_dd8033_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="videoselection",
            index=models.Index(
                fields=["task", "order_index"], name="videos_vide_task_id_ff550a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="videoselection",
            unique_together={("task", "video")},
        ),
    ]
