# Generated by Django 5.0.2 on 2025-12-20 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaybackHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="开始播放时间"),
                ),
                (
                    "last_position",
                    models.FloatField(default=0.0, verbose_name="最后播放位置(秒)"),
                ),
                (
                    "duration_watched",
                    models.FloatField(default=0.0, verbose_name="观看时长(秒)"),
                ),
                ("completed", models.BooleanField(default=False, verbose_name="是否看完")),
                (
                    "completion_percentage",
                    models.FloatField(default=0.0, verbose_name="完成百分比"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "session_id",
                    models.CharField(blank=True, max_length=100, verbose_name="会话ID"),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="用户代理")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playback_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playback_records",
                        to="videos.video",
                        verbose_name="视频",
                    ),
                ),
            ],
            options={
                "verbose_name": "播放历史",
                "verbose_name_plural": "播放历史",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "started_at"],
                        name="videos_play_user_id_285f9c_idx",
                    ),
                    models.Index(
                        fields=["video", "started_at"],
                        name="videos_play_video_i_4ae6c2_idx",
                    ),
                    models.Index(
                        fields=["completed"], name="videos_play_complet_ae8d7c_idx"
                    ),
                ],
                "unique_together": {("user", "video", "session_id")},
            },
        ),
    ]
